dist: xenial
sudo: required

jobs:
  include:
    - name: Job java projects
      language: java
      jdk: openjdk8
      addons:
        apt:
          packages:
            - graphviz
      before_install:
        - chmod +x $GPG_DIR/check_changes
        - check_changes livingdoc-annotations livingdoc-maven-plugin livingdoc-examples || travis_terminate 0;
        - chmod +x $GPG_DIR/deploy_maven
      install: skip
      script: mvn install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -U
      cache:
        directories:
          - "$HOME/.m2"
      after_success:
        - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
        - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
      deploy:
        provider: script
        script: deploy_maven
        skip_cleanup: true
        branches:
          only:
            - master

    - name: Job livingdoc-typescript-plugin
      language: node_js
      node_js: node
      before_install:
        - chmod +x $GPG_DIR/check_changes
        - check_changes livingdoc-typescript-plugin || travis_terminate 0;
        - cd livingdoc-typescript-plugin
      install: npm install
      script: npm run test:ci
      after_success:
        - check_changes src || travis_terminate 0;
        - chmod +x $GPG_DIR/prepare_npm_deploy
        - prepare_npm_deploy
        - npm run build:ci
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branches:
            only:
              - master
              - /release/typescript-plugin/v.*/
        skip_cleanup: true

env:
  global:
    - GPG_DIR="`pwd`/.travis"
    - PATH=$PATH:$GPG_DIR
    - secure: llf7R4RqxrKbM0CDpgAu38bt3ojrPeWbUq/9K8xN4UDCa7FOlbUx5/vlpDzaHSZlW2G04pl1lHjH+Wq9IultDrY7/FmWs8hGrNwEg8ZBKiz9ydImJzgMoJGfjlIgtlLaIksxdU4GesGPehUrk65uyoI2dCsQLunOX5nF9tnbrBcOzg8NngHEp6/p13P07C+ls3XBmTtgbelGTyRG4A1IHXqonwQnhfJyfHOY0nx7IwHnFviK0docJCWq2XWg2XfOHJBtOCS1iQYIoxNEd75M47T9sbir6j5PORV0Y+sGAas8yuAEJvSpwJicWiCMNWTKu06DCZLu3IqMMmS7Mahe77n5R17Eo1MfrIAp/jYj8DpI8vzikaSUxaP8lu3HHSBsEaDq0Q9NgeA0xUi7jbmrMHHJWy9GXxRhK2LOL9mVxYf2a4Lv9qaGeNhxnpggJmBgAjWATatpBwwk/tRlyV79XNgFXXXbU3q7YXGodIDdwQDTcTUqZ9SaP/lGq5Vw4lji1Rosvv8Nfhgoeddxq6I6X1brV6qihn2AFEPmY6lQ+BvW9/QGyjEmtzAK90QsBszNTFQ+HjjAbDcZ5ZqRO6sFM5LL4r8Zd6bwKWE3GruVAcRZ56jfQ0skfBDiPbEwFlxIesG+Ov+qRB1Lh1bSNHkn194JwSvFmRRrgT3VvC7geAg=
    - secure: fNCN2chRkI2DOqNNKs2rxe16mMSovgCKlGtSCu3o7l+hWMRUWeX6LkUvVmV7Jcdz0t4zY6t1H3XtvSM6dZYs9/JCQLXfZGsoonDsClDIVrjOQNF5jFTvQpgdilTq6PowKqiNFO9GvH1C+e0RFyPYp7YetBpaBjGooGx76vTnFfYliUs/EqfWHJhPeA5Uz/Jnx8ayDZLCF5EG6KoSiWS1jOhxAB15L/ei0LVqf0MDzAm9lC+y0kL/ATrEvvBYWuhxY6revS3QWTsB3A5jf7OfvrP3Ii1YQutuUX8SFsjeko8Y3oDCslQ29L3PByJ1gr1hIHQsuYZKKDnZJLhy01NfFccIyITll/bPZJ1sTFUO3IXkBQ0pWwP04Q3CyRugF+DqLAve0iZe+rVwf4hdbBt6/7DspW2ggPq2DbA0pNH+9Db1Dcj/K+O1ldUyFIhpi3Ui0y/FaExL/wasgLsRdGt/92UsVDZjS1DUT3RnVLep9JrvEXLnaf3tJD2p2H8P7YdyR8z036tVotx/3XkZrEu++x1sxy0O2CMuKwyt8lK4YozlepQd98bntr/BpmDJ7rrnNu//vXjwAlNd9PIowHqPdk5W3a52SBPphZvJUc2LWd+KhNlhHI4FMtEIWhKB8oNyWNn0S15jWaXaUtRVGRRqcJneg3e9REr0oX+SaW0Sl2c=
    - secure: bn9fF+BJdxDzsBLMAhHaK5GhDmmRg0nRtRIIDTstPTen+4gskEo/YesA8TV95bExt+1yBWn7xUA7I4vmu9Cn+SIQJb68EuRBSTyKtTtLkMBIwVYBoepmfABZl6cT/DQjafuSKWwIFCmsCpYFAisrGqPVhx7zGKROPdaEM/+RFHmosHkNkP4K3nXaQvyC7TufeaCcORV5mg6L1Vx2fnBzoszkxOjwYSm4e3XWsXtk5xlNBNxlUaBfcxjJwQClzB1JyAmluj0t2q7IK+IsNm5fqeoRABM4o2pE7CfVAqmhOv9oNu4V6g37kTGzUxPzIPCHXRhJapWLgiIxIvloS7A/euDBj/ItbDwi0AYw06uasigZIuY7m8rCofuzyfbu7IhCWva++tXUqvVH0tlBEN5ICIyxPNIZ3e+pOwHTL249cITdACRK2ZzuGQLP1/EZSXN03hwLZpWaUNiXAqAkR45iVBiEVZv8vqvPHaSGAkHSne49MqFB6oyzAliyhDlWHdUyusWhl8HXHXSO5apX6grby38uOexqV/M1Ri9oggG7FYTlQivEbuhqAq41bVZtDC0fZmumQ4PAMY7vrNPl1o2PbyOFK46D8pQR3Uof4+nvwKHASgX221CwjYcn+W5uIFffkg5DaVYmPn12GbfQkjx6iJRgn9FsamgGrtrakg5prmQ=
    - secure: aTHUOAxZzwDrVz0e9B9xJSPBp9zVza3E73WHiyDzsL5j+mAYhiiyeDVLMLlDp0pPOiuds3K1UnSnqaOqJT8C4EWLdhae/TVG2K3jieawbTvPCj3m5Hwqd90wnlPTXM/uwXEtF7yNKib7pmhULzQckQvuGR5SmgbuqfQ13S4AIc3S69xUSNOPXn1LbcCYpzss/Yt6qGrRXJFbgga5hLLLHKL/x7KvMdsjSS3uv2UxJGpvys4UGMx+c5/uHRVTF2Cb1kJ6e8RqVxaDBU/SyS9F/oHJYhF004j2NbnUm8X3HL1W9Vuy5npMIOkyajcwUuIISAIbcTqGkVVIF+rLpRmM7pWlcWde9/Dwpy84+xzaIkw3dDckOLquagBLx8dE/qbcaXbcCyIKTNRBSPqDncguzXLhuffkfKDThZHDuN0al12BBEvazHtWPaghNUfu3dJSiU/5doY8PYpkAHQPt2RjK4YIGqI4jih0XEkDgF63roNHoQttWLOE5FVmGHdGO/qIk/p0cDo/5UYTBcLwDXBLDZxATWF7nupFPMo82s3RC/ZPkt7/+gCqDv44jFaF88TxrTxCdEMzrNTEljY67Rr9y42Xknbo+lEuRAfxHMrb5I8reeyPexsIcEPBN6SSLY5l8Z7Cc3oIWcL15tn1SrJBhmys4RgNsWI6CeVHdIYelQ4=
    - secure: fc5vZkD60K68Mp/B1teDqU1P3dJ153CFT9FqLLQ+q8VJ1keJby+cfkQgrbZ/RtEW6UoobvXTRZjj1l17T77nsxCaKwoDNPeZkiPmQW9be7bwNOk+9IJHXupNmYiqkVSmlN/PWkBdR95X7fWAN6rQ7i5OVo6kxIgHAOcO/ZzvfKDR9DXG5VWgfs58MeSezrjxI/ExI+x2z43V70gdWz1XW8isysBJ1tET9mVaZ55nfFtUjCihoqnL03R94QwP1jX6m2tVRz5CGaNtX0o+iIZ3uHPIzeYZE7NPtpiQ3JLdXKYWs1ApKenqvGqNcez6fI69dyYWqORL6wEqz/8EVMD6bp+dsLFGQiqvSa2lzB7eHBLoLt6iGzpSlg++ZWv9GHdi0lP1H7mCHGLNa/0HFf5cayNme0ZAQzXsJDC3XyLMCluPGWzrgjU+8kSA3M9EU+DF+QPUsS6gDFRmYRefc2rh+pm+rF3HWdVKjhULgr3vTAVWZeGHHFvy5DTC72bXy3aYswf8bbvz4hORsC3ZVBXL+ZqqWU6VPMW1LJxn+1xpmCVTOA6BVcq8iBn7lHO8X7HFG5nZGZSWsR9xva3X8jD4lto296/Ca1DmLXlt7028xsoje6aXm4ylDEUJQTeikXUX9RFbR3BzZ30cnZh9wsxsMdt/rJ6JyYppLgmqBoLW8Vg=
    - secure: C2aMpz744/E/60HtoEtFN5m3wt3gA2DEjgSFN3q8n7QzSA7QTTxms5wHhoX/aQB2e8eaCqxqy9z6mV9o5O1nvfPzynxHHzjmUMU5trSe0nYmwzWM9YujK+t2z6OBZnWLEZV/CDzav58K5l4kmyr94zmaDuAp0uXoZj++xTw9maRmWoDr3c+cMmgiUzSpudtG4XORj7rb7lrOOWHhbIgYc1dUwzgr/FwmQlbZjB4GEmyz668xBXWU3n6eiwgr2ghKMp4SwhTDR4JVPkHdL7EewRTBzS6bNLCJxUoVvVV5I2izmVZXodO9ZudAM809Oth9I0XxzCv7HUyVTumbjyWRMlGxNJuoexRq75kG5OvCc5uEPap0dgSY7U1qs/glyx8RBQ1ka+bM2sOaQ3xpmhXcaas7NsoowXWotUlHdNerOGxIu9aYudbIbFtsAm7FPUNKL52AgZRvHwcriaL/f+fSlJUD6uxVchb3SQQdJWUKGW6eje1fSF2QRokaXw5Aoa/6Wbm//AHkN6ao3eEeV31WN4V7y+v7I7yiulmNjpx9CxB15MxFRRU1k86Kp90WFnQPXiIdP6Tt+UeLdygTYsknlbpEq1ADA30IubteCnagExLyidyi1EKdbl8okZswuxVkxQIjFu/g4i/8s79q1Bww7Dk2XXmLrVROUwHpMdg1/XI=
    - secure: 0taHWTIJPcCFOKHqax5ltXS3JHJpozaoS2p6EqKGfJ4w2InzmN64hOf6wvE8cJiuINXIPdAi0E8FnIeybJP+2wB1Yj/qSHZHKmjpnOTcMheHfhh09/bTSLO+eCj6RINuVqxznHXWUn4cNXPg8hl91ohjtCeGHl9P2JrstAuUWlPL7UGe8uMHLEwYCh45VXuXgGou1dRezqzIem0ZSPpeMq3udtWauQT5yDYDDaWJuxvOdsMG2hLvRkCVBATtweRzZcWniFBpaOeil1Vppypkat1djxEZdfSecKr6YG/93wtIttNTvdtk0ZvpsLnnhThg/LV7DbYUB5Ey0BdzmttFraIZgX5vNzRUzq+Ar+lRDDK7RaeLB0a8IVXAH8swu7BpAI0bPw+KN9gBPF+qk2+WKCJ3yRBPjbFryCEMWDICXx6YGQlXl3Uk1CHBn9tO8nOEYaJ4JLVFBYjtCSjxXp4ibFiypdFpkp1KtF9UgZmj9xujcO88bPQPmn8eCCu11ASC225g4JNePBZFc42cGz3zG9CnboYi84r5uMyn4fUYhqhzMKh4nWBX4T0De8P5GvxfkT2pFskoOm9zyhUdxwkji9xbPRjLNJ2qKWL5L0gQ/PNw+hrFLQkxUAyT5RdHzRLOTDPyPSo+Z6x4dPq6KgoWj9pQxFs6Eo9KAKY+WcizfKc=
    - secure: l+obaoYu8/UrxlWm1lg9TKCxw9WA2J3zmXKD2s/EQJecTpc9R/bKa4OK1Vt1qHtTz1TbaECPW3Bykc5nAw/9Xil+h8z1RKyA/xg8PyguXcwOD6HpnktV3eKy1wLyyUhxmRbwEEQcgOIOjwgD8NMzbNLlD79rxgXVKX8JvLCG1riZv2JOPmPjZedCatjBxhfMwbbRRu8TU8XEDEC/xO65p53cAVlATGLnFL96nDtBw4pJRkx0vpBUi1jTA1/sKOehDRIHBERj02zb2vWe18tw+CNSzmAbX8TVb4fvYmZ4zytxFXAMBXWcj7AIi7/lJnCHhaw/5hWkztafQj8GDP8zvaxao49QGkozROxNhQ6zYCkIQzeUiRIeewIqmdEFwuaTfJ+BvgGAfKaZXmL/1osHLWZ0um8v1yO33ZyDuA5wF7t9iCKLwtNqRCbDQbzIgM3eVTal8dO7rldIC3jRiBn/DGckTKvqX5gr0fV4SQb695LksPKdTKVwbY37FZl9MxA9GYDdZKJr+8VvfLbz8P0KeoZrIe3IaavE5UtHMUnPVRax5rWlU/XgvQaVG+9Bja9042l33fWPoF6E9t4T3D05bkqtVaDX/8ob249E44WJN/V6Y6ApKwV4r+njatvImqpOLOV+up8Yt3MPVXcd9s2r9Gy9cNaYS2av9H54GhxwYtY=

branches:
  only:
    - master

notifications:
  email:
    - julienboz@gmail.com
  on_success: change
  on_failure: always
